name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World!"
      - name: Multi-line shell Command
        run: | 
              echo "This is a multi-line shell Command" 
              echo "This is nice"
      - name: Say Goodbye
        run: echo "Done. Bye"
        
